name: Build and push image to AWS ECR
inputs:
  ECR_REGISTRY:
    required: true
    type: string
  ECR_REPOSITORY:
    required: true
    type: string
  IMAGE_TAG:
    required: true
    type: string
  DOCKERFILE_PATH:
    required: true
    type: string
  DOCKER_CONTEXT:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Build, tag and push image to ecr
      env:
        ECR_REGISTRY: ${{ inputs.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        DOCKERFILE_PATH: ${{ inputs.DOCKERFILE_PATH }}
        DOCKER_CONTEXT: ${{ inputs.DOCKER_CONTEXT }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE_PATH $DOCKER_CONTEXT
        echo "Pushing app image to ECR"
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      shell: bash
