exclude: "^docs/|/migrations/"
default_stages: [commit]


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: ^migrations/
      - id: end-of-file-fixer
        exclude: ^migrations/
      - id: check-yaml
        exclude: ^migrations/
      - id: check-merge-conflict
        exclude: ^migrations/

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^migrations/

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^migrations/

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^migrations/
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]
