version: '3.8'

services:
  flask-chat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: flask-chat-image:prod
    command: gunicorn --bind 0.0.0.0:5000 run:app runserver
    volumes:
      - static_volume:/home/app/web/chezchat/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

  nginx:
    build: ./nginx
    image: flask-chat-nginx-image
    volumes:
      - static_volume:/home/app/web/chezchat/static
    ports:
      - 80:80
    depends_on:
      - flask-chat

volumes:
  static_volume:
