version: '3.8'

services:
  flask-chat:
    container_name: flask-chat
    build: .
    image: flask-chat-image
    volumes:
      - .:/flask-chat
    command: gunicorn --bind 0.0.0.0:5000 --worker-class eventlet -w 1 run:app runserver
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
