version: '3.8'

services:
  flask-chat:
    build: .
    image: flask-chat-image
    volumes:
      - .:/flask-chat
    command: gunicorn -c ./gunicorn.conf.py run:app runserver
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
