version: '3.8'

services:
  flask-chat:
    container_name: flask-chat
    build: .
    image: flask-chat-image
    volumes:
      - .:/flask-chat
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
