name: Provision AWS ECR, build and push image to AWS ECR

on:
  pull_request:
    branches:
      - develop
  release:
    types:
      - published


jobs:
  provision-aws-ecr:
    name: Provision AWS ECR with terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: .github/terraform-ecr/
    env:
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.8

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Initialize Terraform
        id: init
        env:
          TF_STATE_BUCKET: ${{ secrets.AWS_TF_STATE_BUCKET }}
          TF_STATE_OBJECT_KEY: ${{ secrets.AWS_TF_STATE_OBJECT_KEY }}
        run: |
          terraform init \
            -backend-config="bucket=$TF_STATE_BUCKET" \
            -backend-config="key=$TF_STATE_OBJECT_KEY" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="encrypt=true"

      - name: Validate Terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          aws-region: ${{ env.AWS_REGION }}
